# Generated by Django 3.1.2 on 2020-10-31 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangoclasses',
            options={'verbose_name': 'Django Class', 'verbose_name_plural': 'Django Classes'},
        ),
    ]
